// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15WyrgMGdrPk9K8YebVNl5QcTmrvVSFQ',
    appId: '1:1062887481203:web:dc53fc6d90315b3f8fef06',
    messagingSenderId: '1062887481203',
    projectId: 'task-app-9794b',
    authDomain: 'task-app-9794b.firebaseapp.com',
    storageBucket: 'task-app-9794b.appspot.com',
    measurementId: 'G-GX5VVFKXTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwRbNbugq5l1X44KnBUP9-6ACkpIUiRw',
    appId: '1:1062887481203:android:07fa507798d1cb118fef06',
    messagingSenderId: '1062887481203',
    projectId: 'task-app-9794b',
    storageBucket: 'task-app-9794b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNN_Bm1AuyPfJG8pSn_Xy_nscLWcxMfTE',
    appId: '1:1062887481203:ios:c381687c87cde2788fef06',
    messagingSenderId: '1062887481203',
    projectId: 'task-app-9794b',
    storageBucket: 'task-app-9794b.appspot.com',
    iosClientId: '1062887481203-suaue5aefj730v289s2b2ldrsotj27sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNN_Bm1AuyPfJG8pSn_Xy_nscLWcxMfTE',
    appId: '1:1062887481203:ios:c381687c87cde2788fef06',
    messagingSenderId: '1062887481203',
    projectId: 'task-app-9794b',
    storageBucket: 'task-app-9794b.appspot.com',
    iosClientId: '1062887481203-suaue5aefj730v289s2b2ldrsotj27sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC15WyrgMGdrPk9K8YebVNl5QcTmrvVSFQ',
    appId: '1:1062887481203:web:c3cce1b4c820a6128fef06',
    messagingSenderId: '1062887481203',
    projectId: 'task-app-9794b',
    authDomain: 'task-app-9794b.firebaseapp.com',
    storageBucket: 'task-app-9794b.appspot.com',
    measurementId: 'G-N825Z3EF7E',
  );

}